'use strict';
const $=id=>document.getElementById(id),SUITS=['Spades','Hearts','Diamonds','Clubs'],RANKS=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'],SIGNS=['♠','♥','♦','♣'],KEY='hoveybits-solitaire-v1';
let tableau=[],stock=[],waste=[],foundations=[],history=[],selected=null,drawCount=1,completing=false,finishTimer=null,message='';
const board=$('board'),images=new Map();
function card(r,s){return [r,s]};function same(a,b){return a&&b&&a[0]===b[0]&&a[1]===b[1]};function color(s){return s===1||s===2};
function deep(x){return JSON.parse(JSON.stringify(x))}function snapshot(){return deep({tableau,stock,waste,foundations})}function record(){history.push(snapshot());if(history.length>100)history.shift()}
function save(){try{localStorage.setItem(KEY,JSON.stringify({...snapshot(),drawCount,history}))}catch(e){}}
function restore(){try{let x=JSON.parse(localStorage.getItem(KEY));if(!x||!Array.isArray(x.tableau)||x.tableau.length!==7||!Array.isArray(x.foundations)||x.foundations.length!==4||![1,3].includes(x.drawCount))return false;({tableau,stock,waste,foundations,drawCount}=x);history=Array.isArray(x.history)?x.history.slice(-100):[];return true}catch(e){return false}}
function stopFinish(){completing=false;if(finishTimer){clearInterval(finishTimer);finishTimer=null}}
function newGame(){stopFinish();let deck=[];for(let s=0;s<4;s++)for(let r=1;r<=13;r++)deck.push(card(r,s));for(let i=deck.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}tableau=Array.from({length:7},()=>[]);for(let c=0;c<7;c++)for(let j=0;j<=c;j++){let [r,s]=deck.pop();tableau[c].push([r,s,j===c])}stock=deck;waste=[];foundations=[[],[],[],[]];history=[];selected=null;message='Tap stock to draw. Select a card, then a destination.';save();render()}
function undo(){stopFinish();if(history.length){({tableau,stock,waste,foundations}=history.pop());selected=null;message='Move undone.';save()}else message='Nothing to undo.';render()}
function drawStock(){if(completing)return;if(stock.length){record();for(let i=0;i<drawCount&&stock.length;i++)waste.push(stock.pop());message=`Drew up to ${drawCount} card(s).`}else if(waste.length){record();stock=waste.slice().reverse();waste=[];message='Stock recycled.'}else return;selected=null;save();render()}
function sourceCards(src){if(!src)return[];let[k,c,i]=src;if(k==='waste')return waste.length?[waste.at(-1)]:[];if(k==='foundation')return foundations[c].length?[foundations[c].at(-1)]:[];if(k==='tableau'){let pile=tableau[c];return pile[i]?.[2]?pile.slice(i).map(x=>x.slice(0,2)):[]}return[]}
function valid(src,dst){let cards=sourceCards(src);if(!cards.length)return false;let[k,c]=dst,[r,s]=cards[0];if(k==='foundation'){if(cards.length!==1)return false;let p=foundations[c];return !p.length?r===1:p.at(-1)[1]===s&&p.at(-1)[0]+1===r}if(k==='tableau'){if(src[0]==='tableau'&&src[1]===c)return false;let p=tableau[c];return !p.length?r===13:!!p.at(-1)[2]&&p.at(-1)[0]===r+1&&color(p.at(-1)[1])!==color(s)}return false}
function move(src,dst){if(!valid(src,dst))return false;record();let cards=sourceCards(src),[k,c,i]=src;if(k==='waste')waste.pop();else if(k==='foundation')foundations[c].pop();else{tableau[c].splice(i);if(tableau[c].length)tableau[c].at(-1)[2]=true}if(dst[0]==='foundation')foundations[dst[1]].push(...cards);else tableau[dst[1]].push(...cards.map(x=>[...x,true]));selected=null;message='Nice move!';save();render();if(won())$('winDialog').showModal();return true}
function tap(k,c=0,i=0){if(completing)return;if(k==='stock')return drawStock();let src=[k,c,i];if(selected){if(selected[0]===k&&selected[1]===c&&(k!=='tableau'||selected[2]===i)){selected=null;message='Selection cleared.'}else if(move(selected,[k,c]))return;else if(sourceCards(src).length){selected=src;message='Card selected.'}else message='That move is not allowed.'}else if(sourceCards(src).length){selected=src;message='Choose a destination.'}render()}
function auto(){if(completing)return;let sources=[];if(waste.length)sources.push(['waste',0,0]);tableau.forEach((p,c)=>{if(p.length&&p.at(-1)[2])sources.push(['tableau',c,p.length-1])});for(let src of sources)for(let c=0;c<4;c++)if(move(src,['foundation',c]))return;message='No available foundation move.';render()}
function won(){return foundations.reduce((n,p)=>n+p.length,0)===52}
function canFinish(){return !stock.length&&tableau.every(p=>p.every(x=>x[2]))&&!won()}
function finish(){if(!canFinish()||completing)return;record();selected=null;completing=true;message='Completing the foundations…';render();finishTimer=setInterval(finishStep,90)}
function finishStep(){if(!completing)return;for(let r=1;r<=13;r++)for(let s=0;s<4;s++){let c=foundations.findIndex(p=>p.length&&p.at(-1)[1]===s);if(c<0)c=foundations.findIndex(p=>!p.length);if(c<0)continue;let target=foundations[c];if(target.length&&target.at(-1)[0]!==r-1)continue;if(!target.length&&r!==1)continue;let wi=waste.findIndex(x=>x[0]===r&&x[1]===s),ti=-1,idx=-1;if(wi<0){for(let t=0;t<7;t++){let j=tableau[t].findIndex(x=>x[0]===r&&x[1]===s);if(j>=0){ti=t;idx=j;break}}}if(wi<0&&ti<0)continue;if(wi>=0)waste.splice(wi,1);else tableau[ti].splice(idx,1);target.push([r,s]);save();render();return}stopFinish();message=won()?'You won! All 52 cards cleared!':'Could not finish this deal automatically.';save();render();if(won())$('winDialog').showModal()}
function cardImage(r,s){return `assets/deck/${SUITS[s]}_${RANKS[r]}.png`}
function makeCard(x,y,w,h,details){let el=document.createElement('div');el.className='card '+(details.face?'face':'back')+(details.face&&color(details.s)?' red':'')+(details.sel?' selected':'');Object.assign(el.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px',zIndex:details.z||1});if(details.face){let img=document.createElement('img');img.src=cardImage(details.r,details.s);img.alt=`${RANKS[details.r]} of ${SUITS[details.s]}`;let fallback=document.createElement('div');fallback.className='fallback';fallback.innerHTML=`<span>${RANKS[details.r]} ${SIGNS[details.s]}</span><span class="pip">${SIGNS[details.s]}</span><span style="align-self:flex-end;transform:rotate(180deg)">${RANKS[details.r]} ${SIGNS[details.s]}</span>`;img.onerror=()=>{img.remove();el.appendChild(fallback)};el.appendChild(img)}else{let img=document.createElement('img');img.src='assets/deck/Back.png';img.alt='Face-down card';img.onerror=()=>{img.remove();el.textContent='◆'};el.append(img)}if(details.click)el.addEventListener('click',details.click);if(details.dbl)el.addEventListener('dblclick',e=>{e.stopPropagation();details.dbl()});board.appendChild(el);return el}
function slot(x,y,w,h,label,click){let el=document.createElement('div');el.className='slot';Object.assign(el.style,{left:x+'px',top:y+'px',width:w+'px',height:h+'px'});el.textContent=label;el.onclick=click;board.appendChild(el)}
function quickFoundation(src){for(let c=0;c<4;c++)if(move(src,['foundation',c]))return}
function render(){if(!tableau.length)return;board.replaceChildren();let W=board.clientWidth,H=board.clientHeight;if(W<20)return;let gap=Math.max(3,Math.min(13,W*.014)),cw=Math.min(116,(W-gap*8)/7),ch=cw*1.42,left=(W-(cw*7+gap*6))/2,top=6;let X=c=>left+c*(cw+gap),Y=top+ch+Math.max(19,ch*.30),fan=Math.min(ch*.28,Math.max(13,(H-Y-ch-8)/13)),down=Math.max(9,fan*.63);let isSel=(k,c,i)=>selected?.[0]===k&&selected?.[1]===c&&(k!=='tableau'||selected?.[2]===i);
slot(X(0),top,cw,ch,'↻',()=>tap('stock'));if(stock.length)makeCard(X(0),top,cw,ch,{face:false,click:()=>tap('stock'),z:1});
slot(X(1),top,cw,ch,'W',()=>tap('waste'));waste.slice(-3).forEach((v,j,a)=>{let shift=Math.min(cw*.17,Math.max(6,cw*.10)),x=X(1)+j*shift;makeCard(x,top,cw-shift*2,ch,{face:true,r:v[0],s:v[1],z:j+2,sel:j===a.length-1&&isSel('waste',0,0),click:()=>{if(j===a.length-1)tap('waste')},dbl:()=>{if(j===a.length-1)quickFoundation(['waste',0,0])}})});
for(let f=0;f<4;f++){let x=X(f+3),p=foundations[f];slot(x,top,cw,ch,SIGNS[f],()=>tap('foundation',f));if(p.length){let [r,s]=p.at(-1);makeCard(x,top,cw,ch,{face:true,r,s,z:3,sel:isSel('foundation',f,0),click:()=>tap('foundation',f),dbl:()=>quickFoundation(['foundation',f,0])})}}
for(let c=0;c<7;c++){let x=X(c),p=tableau[c];if(!p.length)slot(x,Y,cw,ch,'K',()=>tap('tableau',c,0));let yy=Y;for(let i=0;i<p.length;i++){let[r,s,up]=p[i];makeCard(x,yy,cw,ch,{face:up,r,s,z:i+2,sel:up&&isSel('tableau',c,i),click:()=>tap('tableau',c,i),dbl:()=>{if(up&&i===p.length-1)quickFoundation(['tableau',c,i])}});yy+=up?fan:down}}
$('message').textContent=message;$('mode').textContent=drawCount===1?'Easy · Draw 1':'Hard · Draw 3';$('undo').disabled=!history.length;$('auto').disabled=completing;$('finish').disabled=completing||!canFinish();$('finish').classList.toggle('ready',canFinish()&&!completing)}
$('new').onclick=()=>{if(confirm('Start a new game?'))newGame()};$('mode').onclick=()=>{if(confirm('Switch difficulty and start a new game?')){drawCount=drawCount===1?3:1;newGame()}};$('undo').onclick=undo;$('auto').onclick=auto;$('finish').onclick=finish;$('about').onclick=()=>$('aboutDialog').showModal();$('playAgain').onclick=()=>{$('winDialog').close();newGame()};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&completing)stopFinish();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}});new ResizeObserver(()=>render()).observe(board);if(!restore())newGame();else{message='Welcome back! Your game was restored.';render()}
